#!/data/data/com.termux/files/usr/bin/env fish

set options 'Save to ~/downloads' 'Save to ~/storage/internal/Download' 'Save to ~/storage/sd-card/Download' "Save to $REMOTE/Downloads"
switch (gum choose --header "How to share '$(basename $argv[1])'?" $options || return)
    case $options[1]
        return 0
    case $options[2]
        mv $argv[1] ~/storage/internal/Download
        return
    case $options[3]
        mv $argv[1] ~/storage/sd-card/Download
        return
    case $options[4]
        lftp -c "open $REMOTE/Downloads; put -E '$argv[1]'"
        return
end
