#!/data/data/com.termux/files/usr/bin/env fish

if test -z "$REMOTE"
    echo '$REMOTE environment variable must be set.' >&2
    return 1
end

set target_files
if test -s ~/.config/nnn/.selection
    set lftp_command "open $REMOTE/Downloads; put -E"
    while read --null target
        set lftp_command "$lftp_command '$target'"
    end < ~/.config/nnn/.selection
    lftp -c $lftp_command
else
    set target_files $nnn
    lftp -c "open $REMOTE/Downloads; put -E '$nnn'"
end
