#!/data/data/com.termux/files/usr/bin/env fish
# -------------------------------- #
# Upload selected files to REMOTE. #
# -------------------------------- #

if test -z "$REMOTE"
    echo 'REMOTE environment variable must be set.' >&2
    return 1
end

source (status dirname)/.utils

nnn_get_selection UPLOAD upload $argv[1] || return

set put_options \'$NNN_SELECTION\'
lftp -c "open $REMOTE/Downloads; put -E $put_options"
